version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    container_name: chat_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
